- name: Start docker-machine image
  hosts: tag_docker-machine
  become: true
  vars_files:
    - ./variables.yml
  tasks:
    - name: Install pip 
      apt:
        name: python-pip
        update_cache: yes
        force: yes
        state: present

    - name: Install docker-py
      pip:
        name: docker-py
        umask: "0022"
      become: true      

    - name: Start the image from Docker Hub
      docker_container:
        name: reddit
        image: "{{ my_login }}/otus-reddit:1.0"
        ports: 9292:9292
