concurrent = 4
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "my-runner"
  url = "http://35.205.167.246/"
  token = "318db6de57ae1114d6c56b390d1bf1"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "my-autoscale-runner"
  limit = 2
  url = "http://35.205.167.246"
  token = "2aa4297196be9db30c4ccea1623c83"
  executor = "docker+machine"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
      CredentialsFile = "/home/gitlab-runner/docker-223805-60a93f1a5748.json"
  [runners.machine]
    IdleCount = 0
    IdleTime = 600
    MaxBuilds = 100
    MachineDriver = "google"
    MachineName = "gitlab-ci-%s"
    MachineOptions = ["google-project=docker-223805", "google-machine-type=g1-small", "google-machine-image=ubuntu-os-cloud/global/images/family/ubuntu-1604-lts", "google-tags=gitlab-ci", "google-preemptible=true", "google-zone=europe-west1-d", "google-use-internal-ip=true"]
    OffPeakTimezone = ""
    OffPeakIdleCount = 0
    OffPeakIdleTime = 0
